# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RxTodoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for RxTodoApp

  target 'RxTodoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxTodoAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  # RxTest and RxBlocking make the most sense in the context of unit/integration tests
  target 'RxTodoAppTests' do
      pod 'RxBlocking', '~> 4.0'
      pod 'RxTest',     '~> 4.0'
  end


end
